name: Unit tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TERM: xterm-256color

on:
  pull_request:
    branches:
      - main
    paths:
      - "tests/**"
      - "share/**"
      - "zinit*.zsh"
      - ".github/workflows/tests.yaml"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zunit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest","ubuntu-latest"]
      fail-fast: false

    steps:
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: "install musl"
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes \
            autoconf automake autotools-dev \
            build-essential byacc\
            cmake curl \
            file \
            gcc gettext glibc-source grep \
            libc6 libc6-dev libevent-dev libncurses5-dev libncursesw5-dev libtool libuvc0 lua5.1 \
            m4 \
            ninja-build \
            pkg-config \
            unzip \
            xz-utils \
            zsh

      - name: "install dependencies"
        id: install-deps
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install --force --overwrite autoconf automake binutils byacc cmake coreutils curl gettext gnu-sed libevent libtool libuv lua lua@5.1 make ninja ncurses pkg-config texinfo unzip xz zsh
          brew link --force --overwrite ncurses

      - name: "install zunit"
        id: install-zunit
        run: |
          mkdir -p "$HOME/.local/bin" && echo "$HOME/.local/bin" >> $GITHUB_PATH
          git clone --depth 1 https://github.com/zdharma-continuum/zunit; cd ./zunit
          zsh -c -l './build.zsh' && sudo chmod u+x ./zunit && cp ./zunit "$HOME/.local/bin/"

      - name: "commands"
        run: zunit run tests/commands.zunit

      - name: "annexes"
        run: zunit run tests/annexes.zunit

      # - name: "ices"
      #   run: zunit run tests/ices.zunit

      - name: "snippets"
        run: zunit run tests/snippets.zunit

      - name: "plugins"
        run: zunit run tests/plugins.zunit

      - name: "gh-r"
        run: zunit run tests/gh-r.zunit
